<?php

declare(strict_types=1);

namespace Genaker\Bundle\OroAI\Service;

use Genaker\Bundle\OroAI\Core\Model\LlmRequest;
use Genaker\Bundle\OroAI\Core\Model\LlmResponse;
use Genaker\Bundle\OroAI\Core\Model\ToolResult;

/**
 * Debug transcript of a chat session: EVERYTHING the agent does — every
 * request sent to the AI provider, every response, every tool call/result
 * and the final reply — appended with visual separators to
 * var/cache/{env}/chats/<session_id>.txt (kernel.cache_dir/chats).
 *
 * The session id is generated by the chat widget per conversation, sent with
 * each message and shown in the widget header next to the token counter, so
 * a misbehaving conversation can be matched to its transcript file in
 * seconds. No session id (e.g. API callers that don't send one) = no-op.
 */
class ChatTranscriptLogger
{
    private const string HEAVY_RULE = '================================================================================';
    private const string LIGHT_RULE = '--------------------------------------------------------------------------------';

    private ?string $sessionId = null;

    public function __construct(
        private readonly string $cacheDir,
    ) {
    }

    /** Sanitized to [a-z0-9_-], max 64 chars — the transcript file name. */
    public function setSessionId(?string $sessionId): void
    {
        $clean = strtolower(trim((string) $sessionId));
        $clean = preg_replace('/[^a-z0-9_-]/', '', $clean) ?? '';
        $this->sessionId = $clean !== '' ? substr($clean, 0, 64) : null;
    }

    public function getSessionId(): ?string
    {
        return $this->sessionId;
    }

    public function logUserMessage(string $message): void
    {
        $this->write(self::HEAVY_RULE . "\n" . $this->stamp('USER MESSAGE') . "\n" . self::HEAVY_RULE . "\n"
            . $message . "\n");
    }

    public function logLlmRequest(int $iteration, LlmRequest $request): void
    {
        $toolNames = implode(', ', array_map(static fn($tool) => $tool->name, $request->tools));
        $messages = array_map(
            static fn($message) => [
                'role' => $message->role->value,
                'content' => $message->content,
                'tool_calls' => array_map(
                    static fn($call) => ['name' => $call->name, 'args' => $call->argsJson],
                    $message->toolCalls,
                ),
            ],
            $request->messages,
        );

        $this->write(self::LIGHT_RULE . "\n"
            . $this->stamp(sprintf('LLM REQUEST #%d — %d messages, tools: [%s]', $iteration, count($messages), $toolNames))
            . "\n" . $this->json($messages) . "\n");
    }

    public function logLlmResponse(int $iteration, LlmResponse $response): void
    {
        $this->write(self::LIGHT_RULE . "\n"
            . $this->stamp(sprintf(
                'LLM RESPONSE #%d — finish=%s usage=%s',
                $iteration,
                $response->finishReason ?? '-',
                json_encode($response->usage),
            ))
            . "\n"
            . ($response->content !== '' ? $response->content . "\n" : '')
            . ($response->toolCalls !== []
                ? 'tool_calls: ' . $this->json(array_map(
                    static fn($call) => ['name' => $call->name, 'args' => $call->argsJson],
                    $response->toolCalls,
                )) . "\n"
                : ''));
    }

    public function logToolCall(string $tool, array $args): void
    {
        $this->write(self::LIGHT_RULE . "\n"
            . $this->stamp('TOOL CALL ' . $tool) . "\n" . $this->json($args) . "\n");
    }

    public function logToolResult(string $tool, ToolResult $result): void
    {
        $this->write($this->stamp(sprintf('TOOL RESULT %s (%s)', $tool, $result->success ? 'success' : 'ERROR'))
            . "\n" . $result->toJson() . "\n");
    }

    public function logFinal(string $reply, array $usage, ?array $cost = null): void
    {
        $this->write(self::HEAVY_RULE . "\n"
            . $this->stamp('FINAL REPLY — usage=' . json_encode($usage)
                . ($cost !== null ? ' cost≈$' . ($cost['total'] ?? 0) : ''))
            . "\n" . self::HEAVY_RULE . "\n" . $reply . "\n\n");
    }

    private function stamp(string $title): string
    {
        return '[' . date('Y-m-d H:i:s') . '] ' . $title;
    }

    private function json(mixed $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
            ?: '(unencodable)';
    }

    private function write(string $text): void
    {
        if ($this->sessionId === null) {
            return;
        }

        $dir = rtrim($this->cacheDir, '/') . '/chats';
        if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
            return; // debug logging must never break the chat itself
        }

        @file_put_contents($dir . '/' . $this->sessionId . '.txt', $text, FILE_APPEND | LOCK_EX);
    }
}
